config/routes.rb
Rails.application.routes.draw do
  resources :posts
  resources :usuarios, as: :users, only: [:show, :update]
  resources :friendships, only: [:create, :index, :update]
  devise_for :users, controllers: {
    omniauth_callbacks: "users/omniauth_callbacks"
  }
  authenticated :user do
    root 'main#home'
  end
  unauthenticated :user do
    root 'main#unregistered', as: :unregistered_path
  end
  post "/custom_sign_up", to: "users/omniauth_callbacks#custom_sign_up"
end

app/models/friendship.rb
class Friendship < ApplicationRecord
  belongs_to :user
  belongs_to :friend, class_name: "User"
  validates :user_id, uniqueness: { scope: :friend_id }
  
  def self.friends?(user, friend)
    return true if user == friend
    Friendship.where(user: user, friend: friend).or(Friendship.where(user: friend, friend: user)).any?
  end
  
  def self.pending_for_user(user)
    Friendship.pending.where(friend: user)
  end
  
  def self.accepted_for_user(user)
    Friendship.active.where(friend: user)
  end
  
  include AASM
  aasm column: "status" do
    state :pending, initial: true
    state :active
    state :denied
    
    event :accepted do
      transitions from: [:pending, :denied], to: :active
    end
    
    event :rejected do
      transitions from: [:pending, :active], to: :denied
    end
  end
end

app/controllers/friendships_controller.rb
class FriendshipsController < ApplicationController
    before_action :find_friend, except: [:index, :update]
    before_action :find_friendship, only: :update
    
    def index
        @pending_friendships = current_user.followers.pending
        @accepted_friendships = current_user.followers.active
        @pending_requests = current_user.friendships.pending
    end
    
    def create
        friendship = Friendship.new(user: current_user, friend: @friend)
        respond_to do |format|
            if friendship.save
                format.html { redirect_to @friend }
                format.js
            else
                format.html { redirect_to @friend, notice: "Hubo un error al crear la amistad" }
                format.js
            end
        end
    end
    
    def update
        if params[:status] == "1"
            @friendship.accepted!
        elsif params[:status] == "0"
            @friendship.rejected!
        end
        respond_to do |format|
            format.html { redirect_to friendships_path }
        end
    end
    
    private
        def friendship_params
            params.require(:friendship).permit(:status)
        end
        
        def find_friendship
            @friendship = Friendship.find(params[:id])
        end
end

app/helpers/friendships_helper.rb
module FriendshipsHelper
end

app/views/friendships/_friendship.haml
.large-padding.row.middle-xs.text-left
    = grid xs: 3,sm: 2, md: 1 do
        = circle_img friendship.user.avatar.url(:thumb), 50
    = grid xs: 6, sm: 6, md: 7 do
        = link_to friendship.user.username, friendship.user
    - if friendship.pending?
        = grid xs: 3, sm: 4, md: 4, class: "text-right" do
            = link_to "Aceptar", friendship_path(friendship, status: 1), method: :patch, class: "right-space mdl-button mdl-js-button mdl-button--raised mdl-js-ripple-effect mdl-button--accent"
            = link_to "Denegar", friendship_path(friendship, status: 0), method: :patch, class: "mdl-button mdl-js-button mdl-button--raised mdl-js-ripple-effect mdl-button--colored"

app/views/friendships/index.haml
.row.center-xs
    = grid xs: 10, md: 8 do
        .white.large-padding
            - if @pending_friendships.count > 0
                .border-bottom
                    %p.text-left Amistades pendientes
                    = render @pending_friendships
            - if @accepted_friendships.count > 0
                .border-bottom.top-space
                    %p.text-left Amistades aceptadas
                    = render @accepted_friendships
            - if @pending_requests.count > 0
                .top-space
                    %p.text-left Mis solicitudes pendientes
                    = render @pending_requests