config/routes.rb
Rails.application.routes.draw do
  resources :posts
  resources :usuarios, as: :users, only: [:show, :update]
  resources :friendships, only: [:create, :index, :update]
  devise_for :users, controllers: {
    omniauth_callbacks: "users/omniauth_callbacks"
  }
  authenticated :user do
    root 'main#home'
  end
  unauthenticated :user do
    root 'main#unregistered', as: :unregistered_path
  end
  post "/custom_sign_up", to: "users/omniauth_callbacks#custom_sign_up"
end

app/controllers/usuarios_controller.rb
class UsuariosController < ApplicationController
  before_action :set_user
  before_action :authenticate_user!, only: [:update]
  before_action :authenticate_owner!, only: [:update]
  def show
    @are_friends = current_user.my_friend?(@user)
  end
  
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user }
        format.json { render :show }
        format.js
      else
        format.html { redirect_to @user, notice: @user.errors.full_messages }
        format.json { render json: @user.errors.full_messages}
      end
    end
  end
  
  private
    def set_user
      @user = User.find(params[:id])
    end
    
    def user_params
      params.require(:user).permit(:email, :name, :last_name, :username, :bio, :avatar, :cover)
    end
    
    def authenticate_owner!
      if current_user != @user
        redirect_to root_path, notice: "No estas autorizado", status: :unauthorized
      end
    end
end

app/views/usuarios/_images_menu.haml
.absolute{style: "top: 10px; right: 10px;"}
    %button#images_menu.mdl-button.mdl-js-button.mdl-button--icon
        %i.material-icons more_vert
    %ul.mdl-menu.mdl-menu--bottom-right.mdl-js-menu.mdl-js-ripple-effect{for: "images_menu"}
        %li.mdl-menu__item.file-activator{for: "#user_avatar"} Actualizar avatar
        %li.mdl-menu__item.file-activator{for: "#user_cover"} Actualizar Cover

app/views/usuarios/show.haml
.top-space
  .row.center-xs
    = grid md: 6, sm: 8, xs: 10, lg: 4 do
      .white.mdl-shadow--2dp.relative.top-space
        / Cover del usuario
        .big-padding.white-text.text-left.cover.relative#user-cover{style: "background-image: url(#{@user.cover.url(:medium)});"}
          - if current_user == @user
            = render "usuarios/images_menu"
          #user-avatar
            = circle_img @user.avatar.url(:medium)
        %section.border-bottom.large-padding
          .row.middle-xs
            = grid class: "col-xs" do
              %h1.big.no-margin
                = best_in_place_if current_user == @user, @user, :name
                = best_in_place_if current_user == @user, @user, :last_name
              %span= best_in_place_if current_user == @user, @user, :username
            - unless @are_friends
              = grid xs: 4 do
                = button_to friendships_path(friend_id: @user.id), method: :post, :"data-type" => "script", remote: true, class: "mdl-button mdl-js-button mdl-button--raised mdl-js-ripple-effect mdl-button--accent" do
                  %i.material-icons.small person_add
                  Agregar
        .large-padding
          .row
            = grid class: "col-xs" do
              20
              Seguidores
            = grid class: "col-xs" do
              = pluralize(@user.posts.count, "post")
          .row.center-xs.top-space
            = grid md: 10, xs: 8 do
              %span= best_in_place_if current_user == @user, @user, :bio, as: :textarea
        .top-space
          = form_for @user, remote: true do |f|
            = f.file_field :avatar, class: "remotipart"
          = form_for @user, remote: true do |f|
            = f.file_field :cover, class: "remotipart"